"""
Package the configured bot and submit it to Kaggle.

Config: scripts/submission/config.json

Fields:
  bot         — module path to the bot (e.g. bots.heuristic.sniper:agent_fn)
  message     — submission message shown on Kaggle
  competition — Kaggle competition slug (default: orbit-wars)
"""
import ast
import importlib
import inspect
import json
import os
import re
import subprocess
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from experiments.logger import save as log_experiment

CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")

SUBMISSION_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "submission", "main.py"
)

HEADER = '''"""
Kaggle submission entry point — auto-generated by scripts/submission/run.py.
Do not edit manually. Re-run the script to update.
"""
import math
'''


def _relative_imports(source_text: str) -> list[str]:
    """Return module names from relative imports (e.g. 'predictor' from 'from .predictor import ...')."""
    try:
        tree = ast.parse(source_text)
    except SyntaxError:
        return []
    return [
        node.module
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom) and node.level > 0 and node.module
    ]


def _collect_inline_modules(package_dir: str, entry_file: str) -> list[tuple[str, str]]:
    """Return (name, source) pairs for all relative dependencies in topological order."""
    visited: set[str] = set()
    order: list[tuple[str, str]] = []

    def visit(module_name: str) -> None:
        if module_name in visited:
            return
        visited.add(module_name)
        filepath = os.path.join(package_dir, module_name + ".py")
        if not os.path.exists(filepath):
            return
        with open(filepath) as f:
            src = f.read()
        for dep in _relative_imports(src):
            visit(dep)
        order.append((module_name, src))

    with open(entry_file) as f:
        entry_src = f.read()
    for dep in _relative_imports(entry_src):
        visit(dep)
    return order


def _strip_relative_imports(source_text: str) -> str:
    """Remove relative import lines and duplicate stdlib imports from a module source."""
    lines = [
        line for line in source_text.splitlines()
        if not line.strip().startswith("from .")
        and line.strip() != "import math"
    ]
    return "\n".join(lines).strip()


def package_bot(bot_spec: str) -> None:
    module_path, attr = bot_spec.rsplit(":", 1)
    module = importlib.import_module(module_path)
    fn = getattr(module, attr)

    if inspect.isfunction(fn):
        source = inspect.getsource(fn)
        source = source.replace("def agent_fn(", "def agent(", 1)
        body = source
    else:
        class_name = type(fn).__name__
        cls = type(fn)

        # Collect and inline relative-import dependencies
        bot_file = inspect.getfile(cls)
        package_dir = os.path.dirname(bot_file)
        inline_modules = _collect_inline_modules(package_dir, bot_file)
        inline_blocks = [_strip_relative_imports(src) for _, src in inline_modules]

        class_source = inspect.getsource(cls)
        class_source = "\n".join(
            line for line in class_source.splitlines()
            if not (line.strip().startswith("from bots.") or line.strip().startswith("import bots."))
        )
        class_source = re.sub(
            r"class " + re.escape(class_name) + r"\s*\(\w+\)\s*:",
            "class " + class_name + ":",
            class_source,
        )

        body = (
            "\n\n".join(inline_blocks)
            + ("\n\n" if inline_blocks else "")
            + class_source
            + "\n\n"
            + f"_bot = {class_name}()"
            + "\n\n"
            + "def agent(obs, config=None):\n"
            + "    return _bot.act(obs, config)\n"
        )

    with open(SUBMISSION_PATH, "w") as f:
        f.write(HEADER + "\n" + body + "\n")

    print(f"Packaged:  {bot_spec}")
    print(f"Output:    {SUBMISSION_PATH}")


def main():
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)

    bot = cfg["bot"]
    message = cfg["message"]
    competition = cfg.get("competition", "orbit-wars")
    save_log = cfg.get("save_log", True)

    package_bot(bot)

    print(f"Submitting to: {competition}")
    print(f"Message:       {message}\n")

    result = subprocess.run(
        ["kaggle", "competitions", "submit", competition,
         "-f", SUBMISSION_PATH, "-m", message],
        capture_output=False,
    )

    success = result.returncode == 0
    if save_log:
        log_path = log_experiment("submissions", {
            "bot": bot,
            "message": message,
            "competition": competition,
            "success": success,
        }, label=message)
        print(f"Log:  {log_path}")

    if not success:
        print("\nSubmission failed. Make sure KAGGLE_API_TOKEN is set.")
        sys.exit(1)


if __name__ == "__main__":
    main()
