"""
Package the configured bot and submit it to Kaggle.

Config: scripts/submission/config.json

Fields:
  bot         — module path to the bot (e.g. bots.heuristic.sniper:agent_fn)
  message     — submission message shown on Kaggle
  competition — Kaggle competition slug (default: orbit-wars)
"""
import importlib
import inspect
import json
import os
import subprocess
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from experiments.logger import save as log_experiment

CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")

SUBMISSION_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "submission", "main.py"
)

HEADER = '''"""
Kaggle submission entry point — auto-generated by scripts/submission/run.py.
Do not edit manually. Re-run the script to update.
"""
import math
'''


def package_bot(bot_spec: str) -> None:
    module_path, attr = bot_spec.rsplit(":", 1)
    module = importlib.import_module(module_path)
    fn = getattr(module, attr)

    if inspect.isfunction(fn):
        source = inspect.getsource(fn)
        source = source.replace("def agent_fn(", "def agent(", 1)
        body = source
    else:
        act_source = inspect.getsource(type(fn).act)
        lines = act_source.splitlines()
        body_lines = lines[1:]
        body = textwrap.dedent("\n".join(body_lines))
        body = "def agent(obs, config=None):\n" + textwrap.indent(body, "    ")

    with open(SUBMISSION_PATH, "w") as f:
        f.write(HEADER + "\n" + body + "\n")

    print(f"Packaged:  {bot_spec}")
    print(f"Output:    {SUBMISSION_PATH}")


def main():
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)

    bot = cfg["bot"]
    message = cfg["message"]
    competition = cfg.get("competition", "orbit-wars")
    save_log = cfg.get("save_log", True)

    package_bot(bot)

    print(f"Submitting to: {competition}")
    print(f"Message:       {message}\n")

    result = subprocess.run(
        ["kaggle", "competitions", "submit", competition,
         "-f", SUBMISSION_PATH, "-m", message],
        capture_output=False,
    )

    success = result.returncode == 0
    if save_log:
        log_path = log_experiment("submissions", {
            "bot": bot,
            "message": message,
            "competition": competition,
            "success": success,
        }, label=message)
        print(f"Log:  {log_path}")

    if not success:
        print("\nSubmission failed. Make sure KAGGLE_API_TOKEN is set.")
        sys.exit(1)


if __name__ == "__main__":
    main()
