"""
Kaggle submission entry point — auto-generated by scripts/submission/package_neural.py.
Do not edit manually.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
import numpy as np
import torch
import torch.nn as nn


# === types.py ===
"""Pure-numpy intermediate structs for the neural bot. No PyTorch imports."""




@dataclass
class ActionContext:
    planet_ids: np.ndarray       # shape (n,) int32
    planet_positions: np.ndarray # shape (n, 2) float32 — raw x, y (not normalized)
    my_planet_mask: np.ndarray   # shape (n,) bool
    n_planets: int


@dataclass
class ModelInput:
    array: np.ndarray   # shape (D,) float32
    context: ActionContext


@dataclass
class ModelLabels:
    action_type: int    # 0 = NO_OP, 1 = LAUNCH
    source_idx: int     # -1 if NO_OP
    target_idx: int     # -1 if NO_OP
    amount_bin: int     # -1 if NO_OP
    value_target: float


# === state_builder.py ===
"""StateBuilder: converts a StepRecord or live obs dict into a padded, normalized ModelInput."""





class StateBuilder:
    def __init__(self, max_planets: int = 50, max_fleets: int = 100) -> None:
        self.max_planets = max_planets
        self.max_fleets = max_fleets

    @property
    def input_dim(self) -> int:
        return self.max_planets * 7 + self.max_fleets * 7

    def from_obs(self, obs: dict, player: int) -> ModelInput:
        raw_planets = obs["planets"]
        raw_fleets = obs["fleets"]

        if len(raw_planets) == 0:
            planets = np.empty((0, 7), dtype=np.float32)
        else:
            planets = np.array(raw_planets, dtype=np.float32)

        if len(raw_fleets) == 0:
            fleets = np.empty((0, 7), dtype=np.float32)
        else:
            fleets = np.array(raw_fleets, dtype=np.float32)

        return self._build(planets, fleets, player)

    def from_step(self, step: StepRecord, player: int) -> ModelInput:
        return self._build(step.planets, step.fleets, player)

    def __call__(self, step: StepRecord, player: int) -> ModelInput:
        return self.from_step(step, player)

    def _build(self, planets: np.ndarray, fleets: np.ndarray, player: int) -> ModelInput:
        context = self._build_context(planets, player)
        array = self._build_array(planets, fleets, player)
        return ModelInput(array=array, context=context)

    def _build_context(self, planets: np.ndarray, player: int) -> ActionContext:
        if planets.shape[0] == 0:
            return ActionContext(
                planet_ids=np.empty(0, dtype=np.int32),
                planet_positions=np.empty((0, 2), dtype=np.float32),
                my_planet_mask=np.empty(0, dtype=bool),
                n_planets=0,
            )

        planet_ids = planets[:, 0].astype(np.int32)
        planet_positions = planets[:, 2:4].astype(np.float32)
        my_planet_mask = (planets[:, 1] == player)
        n_planets = len(planet_ids)

        return ActionContext(
            planet_ids=planet_ids,
            planet_positions=planet_positions,
            my_planet_mask=my_planet_mask,
            n_planets=n_planets,
        )

    def _build_array(self, planets: np.ndarray, fleets: np.ndarray, player: int) -> np.ndarray:
        out = np.zeros(self.input_dim, dtype=np.float32)

        n_planets = min(planets.shape[0], self.max_planets)
        for i in range(n_planets):
            row = planets[i]
            owner = row[1]
            x = row[2]
            y = row[3]
            ships = row[5]
            production = row[6]
            offset = i * 7
            out[offset + 0] = float(owner == player)
            out[offset + 1] = float(owner not in (-1, player))
            out[offset + 2] = float(owner == -1)
            out[offset + 3] = x / 100.0
            out[offset + 4] = y / 100.0
            out[offset + 5] = float(np.clip(ships / 200.0, 0.0, 1.0))
            out[offset + 6] = production / 5.0

        n_fleets = min(fleets.shape[0], self.max_fleets)
        fleet_base = self.max_planets * 7
        for i in range(n_fleets):
            row = fleets[i]
            owner = row[1]
            x = row[2]
            y = row[3]
            angle = row[4]
            ships = row[6]
            offset = fleet_base + i * 7
            out[offset + 0] = float(owner == player)
            out[offset + 1] = float(owner != player)
            out[offset + 2] = x / 100.0
            out[offset + 3] = y / 100.0
            out[offset + 4] = math.sin(angle)
            out[offset + 5] = math.cos(angle)
            out[offset + 6] = float(np.clip(ships / 200.0, 0.0, 1.0))

        return out


# === action_codec.py ===
"""ActionCodec: encodes raw dataset actions to ModelLabels."""





class ActionCodec:
    NO_OP = 0
    LAUNCH = 1

    def __init__(self, n_amount_bins: int = 5) -> None:
        self.n_amount_bins = n_amount_bins
        self.BINS = [0.1, 0.25, 0.5, 0.75, 1.0]

    def encode(
        self,
        raw_actions: np.ndarray,
        context: ActionContext,
        planets: np.ndarray,
        value_target: float,
    ) -> ModelLabels:
        if raw_actions.shape[0] == 0:
            return ModelLabels(
                action_type=self.NO_OP,
                source_idx=-1,
                target_idx=-1,
                amount_bin=-1,
                value_target=value_target,
            )

        dominant = raw_actions[np.argmax(raw_actions[:, 2])]

        from_planet_id = int(dominant[0])
        matches = np.where(context.planet_ids == from_planet_id)[0]
        if len(matches) == 0:
            return ModelLabels(
                action_type=self.NO_OP,
                source_idx=-1,
                target_idx=-1,
                amount_bin=-1,
                value_target=value_target,
            )
        source_idx = int(matches[0])

        if context.n_planets <= 1:
            return ModelLabels(
                action_type=self.NO_OP,
                source_idx=-1,
                target_idx=-1,
                amount_bin=-1,
                value_target=value_target,
            )

        recorded_angle = float(dominant[1])
        source_pos = context.planet_positions[source_idx]
        source_x = float(source_pos[0])
        source_y = float(source_pos[1])

        best_idx = -1
        best_diff = float("inf")
        for j in range(context.n_planets):
            if j == source_idx:
                continue
            cand_pos = context.planet_positions[j]
            dx = float(cand_pos[0]) - source_x
            dy = float(cand_pos[1]) - source_y
            direction = math.atan2(dy, dx)
            diff_raw = direction - recorded_angle
            angular_diff = abs(((diff_raw + math.pi) % (2 * math.pi)) - math.pi)
            if angular_diff < best_diff:
                best_diff = angular_diff
                best_idx = j
        target_idx = best_idx

        n_ships = float(dominant[2])
        source_ships = float(planets[source_idx, 5])
        if source_ships <= 0:
            fraction = self.BINS[-1]
        else:
            fraction = float(np.clip(n_ships / source_ships, 0.0, 1.0))

        bins_arr = np.array(self.BINS, dtype=np.float32)
        amount_bin = int(np.argmin(np.abs(bins_arr - fraction)))

        return ModelLabels(
            action_type=self.LAUNCH,
            source_idx=source_idx,
            target_idx=target_idx,
            amount_bin=amount_bin,
            value_target=value_target,
        )

    def decode(self, output, context: ActionContext, planets: np.ndarray) -> list:
        """Decode a PolicyOutput into a list of game actions.

        output: PolicyOutput (from model.py) — may be batched (B=1 already squeezed by caller)
        context: ActionContext for the current turn
        planets: (n_planets, 7) float32 array — for available ships
        Returns: [] for NO_OP, or [[planet_id, angle, n_ships]] for LAUNCH
        """
        if context.n_planets == 0:
            return []

        # 1. Action type
        action_type_logits = output.action_type_logits
        if hasattr(action_type_logits, "cpu"):
            action_type_logits = action_type_logits.cpu().numpy()
        if int(np.argmax(action_type_logits)) == self.NO_OP:
            return []

        # 2. Source: argmax over source_logits masked to my_planet_mask
        source_logits = output.source_logits
        if hasattr(source_logits, "cpu"):
            source_logits = source_logits.cpu().numpy()
        source_logits = source_logits[:context.n_planets].copy()

        my_mask = context.my_planet_mask
        if not my_mask.any():
            return []
        source_logits[~my_mask] = -np.inf
        source_idx = int(np.argmax(source_logits))

        # 3. Target: argmax over target_logits excluding source_idx
        target_logits = output.target_logits
        if hasattr(target_logits, "cpu"):
            target_logits = target_logits.cpu().numpy()
        target_logits = target_logits[:context.n_planets].copy()
        target_logits[source_idx] = -np.inf
        if np.all(np.isneginf(target_logits)):
            return []
        target_idx = int(np.argmax(target_logits))

        # 4. Amount bin
        amount_logits = output.amount_logits
        if hasattr(amount_logits, "cpu"):
            amount_logits = amount_logits.cpu().numpy()
        amount_bin = int(np.argmax(amount_logits))
        amount_bin = int(np.clip(amount_bin, 0, len(self.BINS) - 1))

        # 5. Ships to send
        if planets.shape[0] > source_idx:
            source_ships = float(planets[source_idx, 5])
        else:
            return []
        n_ships = self.BINS[amount_bin] * source_ships
        if n_ships < 1.0:
            return []

        # 6. Angle from source to target
        source_pos = context.planet_positions[source_idx]
        target_pos = context.planet_positions[target_idx]
        angle = math.atan2(
            float(target_pos[1]) - float(source_pos[1]),
            float(target_pos[0]) - float(source_pos[0]),
        )

        source_planet_id = int(context.planet_ids[source_idx])
        return [[source_planet_id, angle, n_ships]]


# === model.py ===
"""PolicyValueModel and PolicyOutput — PyTorch neural network for Orbit Wars."""





@dataclass
class PolicyOutput:
    action_type_logits: torch.Tensor  # (B, 2)
    source_logits: torch.Tensor       # (B, MAX_PLANETS)
    target_logits: torch.Tensor       # (B, MAX_PLANETS)
    amount_logits: torch.Tensor       # (B, N_BINS)
    value: torch.Tensor               # (B, 1)


@dataclass
class PolicyValueConfig:
    input_dim: int
    hidden_dims: list

    max_planets: int = 50
    n_amount_bins: int = 5
    dropout: float = 0.1


class PolicyValueModel(nn.Module):
    def __init__(self, config: PolicyValueConfig) -> None:
        super().__init__()
        self.config = config

        # Build MLP encoder as a public nn.Sequential (swappable in future)
        layers: list[nn.Module] = []
        in_dim = config.input_dim
        for h_dim in config.hidden_dims:
            layers.append(nn.Linear(in_dim, h_dim))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(config.dropout))
            in_dim = h_dim
        self.encoder = nn.Sequential(*layers)

        repr_dim = config.hidden_dims[-1]
        self.action_type_head = nn.Linear(repr_dim, 2)
        self.source_head = nn.Linear(repr_dim, config.max_planets)
        self.target_head = nn.Linear(repr_dim, config.max_planets)
        self.amount_head = nn.Linear(repr_dim, config.n_amount_bins)
        self.value_head = nn.Linear(repr_dim, 1)

    def forward(self, state: torch.Tensor) -> PolicyOutput:
        shared = self.encoder(state)
        return PolicyOutput(
            action_type_logits=self.action_type_head(shared),
            source_logits=self.source_head(shared),
            target_logits=self.target_head(shared),
            amount_logits=self.amount_head(shared),
            value=torch.tanh(self.value_head(shared)),
        )


# === bot.py ===
"""NeuralBot — inference wrapper around PolicyValueModel."""





class NeuralBot:
    def __init__(
        self,
        model: PolicyValueModel,
        state_builder: StateBuilder,
        codec: ActionCodec,
        device: str = "cpu",
    ) -> None:
        self.model = model
        self.state_builder = state_builder
        self.codec = codec
        self.device = device
        self.model.to(device)
        self.model.eval()

    @property
    def name(self) -> str:
        return "neural"

    def act(self, obs, config=None) -> list:
        if isinstance(obs, dict):
            player = obs.get("player", 0)
            raw_planets = obs.get("planets", [])
            model_input = self.state_builder.from_obs(obs, player)
        else:
            player = obs.player
            raw_planets = list(obs.planets) if hasattr(obs.planets, "__iter__") else obs.planets
            model_input = self.state_builder.from_step(obs, player)

        tensor = torch.from_numpy(model_input.array).unsqueeze(0).to(self.device)

        with torch.no_grad():
            output = self.model(tensor)

        output_single = PolicyOutput(
            action_type_logits=output.action_type_logits[0],
            source_logits=output.source_logits[0],
            target_logits=output.target_logits[0],
            amount_logits=output.amount_logits[0],
            value=output.value[0],
        )

        if len(raw_planets) > 0:
            planets_arr = np.array(raw_planets, dtype=np.float32)
        else:
            planets_arr = np.empty((0, 7), dtype=np.float32)

        return self.codec.decode(output_single, model_input.context, planets_arr)

    @classmethod
    def load(cls, path: str, device: str = "cpu") -> "NeuralBot":
        """Load a NeuralBot from a checkpoint file.

        Checkpoint format:
            {
                "config": PolicyValueConfig,
                "state_dict": dict,
                "max_planets": int,
                "max_fleets": int,
                "n_amount_bins": int,
            }
        """
        checkpoint = torch.load(path, map_location=device)
        config: PolicyValueConfig = checkpoint["config"]
        max_planets = checkpoint.get("max_planets", config.max_planets)
        max_fleets = checkpoint.get("max_fleets", 100)
        n_amount_bins = checkpoint.get("n_amount_bins", config.n_amount_bins)

        model = PolicyValueModel(config)
        model.load_state_dict(checkpoint["state_dict"])

        state_builder = StateBuilder(max_planets=max_planets, max_fleets=max_fleets)
        codec = ActionCodec(n_amount_bins=n_amount_bins)

        return cls(model=model, state_builder=state_builder, codec=codec, device=device)


# Module-level agent_fn for kaggle_environments compatibility
# Uses a default untrained model; replace with NeuralBot.load() after training.
_default_bot: NeuralBot | None = None


def agent_fn(obs, config=None):
    global _default_bot
    if _default_bot is None:
        _cfg = PolicyValueConfig(
            input_dim=StateBuilder().input_dim,
            hidden_dims=[256, 128],
        )
        _default_bot = NeuralBot(
            model=PolicyValueModel(_cfg),
            state_builder=StateBuilder(),
            codec=ActionCodec(),
        )
    return _default_bot.act(obs, config)


# === AGENT ENTRY POINT (random weights) ===
_bot = None


def agent(obs, config=None):
    """Entry point for Kaggle submission — random weights (no checkpoint)."""
    global _bot
    if _bot is None:
        _cfg = PolicyValueConfig(
            input_dim=StateBuilder().input_dim,
            hidden_dims=[256, 128],
        )
        _bot = NeuralBot(
            model=PolicyValueModel(_cfg),
            state_builder=StateBuilder(),
            codec=ActionCodec(),
        )
    return _bot.act(obs, config)
