"""Copy the current best bot into submission/main.py as a self-contained agent."""
import argparse
import importlib
import inspect
import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SUBMISSION_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "submission", "main.py"
)

HEADER = '''"""
Kaggle submission entry point — auto-generated by scripts/package_submission.py.
Do not edit manually. Re-run the script to update.
"""
import math
'''

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Package a bot for Kaggle submission.")
    parser.add_argument(
        "--bot",
        default="bots.heuristic.sniper:agent_fn",
        help="Bot to package as module.path:attr (default: bots.heuristic.sniper:agent_fn)",
    )
    args = parser.parse_args()

    module_path, attr = args.bot.rsplit(":", 1)
    module = importlib.import_module(module_path)
    fn = getattr(module, attr)

    if inspect.isfunction(fn):
        # Plain function bot — extract source directly
        source = inspect.getsource(fn)
        source = source.replace("def agent_fn(", "def agent(", 1)
        body = source
    else:
        # Callable class instance (e.g. agent_fn = SniperBot())
        # NOTE: bots that use self.attribute state are not compatible with this
        # packaging approach — only the act() method body is inlined.
        act_source = inspect.getsource(type(fn).act)
        lines = act_source.splitlines()
        # Skip the def act(self, ...) declaration line
        body_lines = lines[1:]
        # Remove common leading whitespace
        body = textwrap.dedent("\n".join(body_lines))
        body = "def agent(obs, config=None):\n" + textwrap.indent(body, "    ")

    with open(SUBMISSION_PATH, "w") as f:
        f.write(HEADER + "\n" + body + "\n")

    print(f"Wrote submission to {SUBMISSION_PATH}")
    print("Test it with: python -c \"from submission.main import agent; print(agent({}))\"")
